if object_id('SP_HotelRoomRatePlanImportOneMonth') is not null
drop proc SP_HotelRoomRatePlanImportOneMonth
GO
create proc SP_HotelRoomRatePlanImportOneMonth
@start datetime,
@end datetime
as
insert into T_CtripHotelRoomRatePlan([HotelId]
      ,[RoomTypeCode]
      ,[AmountBeforeTax]
      ,[ListPrice]
      ,[BackAmount]
      ,[BackCode]
      ,[BackCurrencyCode]
      ,[BackDescription]
      ,[Breakfast]
      ,[NumberOfBreakfast]
      ,[CancelAmount]
      ,[CancelCurrencyCode]
      ,[CancelPenaltyEndTime]
      ,[CancelPenaltyStartTime]
      ,[CurrencyCode]
      ,[EndPeriod]
      ,[EndTime]
      ,[GuaranteeCode]
      ,[HoldTime]
      ,[NumberOfGuests]
      ,[ProgramName]
      ,[StartPeriod]
      ,[StartTime]
      ,[Status]
      ,[AddDate]
      ,[UpdateTime]
      ,[RatePlanCategory]
      ,[MarketCode]
      ,[IsInstantConfirm]
      ,[Pertain])
select [HotelId]
      ,[RoomTypeCode]
      ,[AmountBeforeTax]
      ,[ListPrice]
      ,[BackAmount]
      ,[BackCode]
      ,[BackCurrencyCode]
      ,[BackDescription]
      ,[Breakfast]
      ,[NumberOfBreakfast]
      ,[CancelAmount]
      ,[CancelCurrencyCode]
      ,[CancelPenaltyEndTime]
      ,[CancelPenaltyStartTime]
      ,[CurrencyCode]
      ,[EndPeriod]
      ,[EndTime]
      ,[GuaranteeCode]
      ,[HoldTime]
      ,[NumberOfGuests]
      ,[ProgramName]
      ,[StartPeriod]
      ,[StartTime]
      ,[Status]
      ,[AddDate]
      ,[UpdateTime]
      ,[RatePlanCategory]
      ,[MarketCode]
      ,[IsInstantConfirm]
      ,[Pertain] from T_CtripHotelRoomRatePlanRecord
	  where StartTime>=@start and EndTime<@end
